/* PEDIDOS SIMULADOS: incluyen siete estados. */
window.ORDERS = [
  {
    id: "SZ-1048",
    client: "Laura Gómez",
    date: "2026-07-13",
    products: "Audífonos Nova Pro",
    qty: 1,
    type: "Detal",
    total: 129900,
    payment: "Nequi",
    pay: "Pagado",
    status: "Pendiente",
    city: "Bogotá",
    carrier: "Por asignar",
    tracking: "—",
  },
  {
    id: "SZ-1047",
    client: "Carlos Méndez",
    date: "2026-07-12",
    products: "Morral Atlas + Teclado",
    qty: 2,
    type: "Detal",
    total: 329800,
    payment: "Tarjeta",
    pay: "Pagado",
    status: "Confirmado",
    city: "Medellín",
    carrier: "Coordinadora",
    tracking: "COO882190",
  },
  {
    id: "SZ-1046",
    client: "Mariana Ruiz",
    date: "2026-07-12",
    products: "Bolso Siena",
    qty: 1,
    type: "Detal",
    total: 169900,
    payment: "Daviplata",
    pay: "Pagado",
    status: "Preparando",
    city: "Cali",
    carrier: "Servientrega",
    tracking: "SER442801",
  },
  {
    id: "SZ-1045",
    client: "Distribuciones Prisma",
    date: "2026-07-11",
    products: "Nova Pro + Fresh Route",
    qty: 18,
    type: "Mayor",
    total: 1708200,
    payment: "Transferencia",
    pay: "Pagado",
    status: "Empacado",
    city: "Pereira",
    carrier: "TCC",
    tracking: "TCC110239",
  },
  {
    id: "SZ-1044",
    client: "Juan Esteban Díaz",
    date: "2026-07-10",
    products: "Executive Steel",
    qty: 1,
    type: "Detal",
    total: 249900,
    payment: "Contra entrega",
    pay: "Pendiente",
    status: "Enviado",
    city: "Bucaramanga",
    carrier: "Interrapidísimo",
    tracking: "INT901188",
  },
  {
    id: "SZ-1043",
    client: "Valentina Castro",
    date: "2026-07-09",
    products: "Vestido Aura Midi",
    qty: 1,
    type: "Detal",
    total: 159900,
    payment: "Tarjeta",
    pay: "Pagado",
    status: "Entregado",
    city: "Barranquilla",
    carrier: "Servientrega",
    tracking: "SER908821",
  },
  {
    id: "SZ-1042",
    client: "Andrés Pardo",
    date: "2026-07-08",
    products: "Smartwatch Pulse S4",
    qty: 1,
    type: "Detal",
    total: 189900,
    payment: "Nequi",
    pay: "Reembolsado",
    status: "Cancelado",
    city: "Manizales",
    carrier: "—",
    tracking: "—",
  },
  {
    id: "SZ-1041",
    client: "Comercializadora Uno",
    date: "2026-07-07",
    products: "Bolso Siena + Flor de Seda",
    qty: 30,
    type: "Mayor",
    total: 3522000,
    payment: "Transferencia",
    pay: "Pagado",
    status: "Entregado",
    city: "Cartagena",
    carrier: "TCC",
    tracking: "TCC883102",
  },
  {
    id: "SZ-1040",
    client: "Carlos Méndez",
    date: "2026-07-06",
    products: "Chaqueta Urban Motion",
    qty: 1,
    type: "Detal",
    total: 219900,
    payment: "Tarjeta",
    pay: "Pagado",
    status: "Entregado",
    city: "Medellín",
    carrier: "Coordinadora",
    tracking: "COO551020",
  },
  {
    id: "SZ-1039",
    client: "Mariana Ruiz",
    date: "2026-07-05",
    products: "Bloom + Rosé Velvet",
    qty: 2,
    type: "Detal",
    total: 349800,
    payment: "Daviplata",
    pay: "Pagado",
    status: "Enviado",
    city: "Cali",
    carrier: "Servientrega",
    tracking: "SER330942",
  },
];
